################################################################################
# \file defines_pse8xxgp.mk
#
# \brief
# Defines, needed for the PSOC(TM) Edge build recipe.
#
################################################################################
# \copyright
# Copyright (c) 2026, Infineon Technologies AG, or an affiliate of
# Infineon Technologies AG. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

#
# Architecture specifics
#
_MTB_RECIPE__JLINK_DEVICE_CM0_CFG:=PSE84x_CM0p
_MTB_RECIPE__OPENOCD_DEVICE_CFG:=infineon/pse84xgxs2.cfg
_MTB_RECIPE__IDE_TEMPLATE_TARGET_DIR=pse8xxgp
ifneq ($(filter EPC4,$(DEVICE_$(DEVICE)_FEATURES)),)
_MTB_RECIPE__OPENOCD_DEVICE_CFG:=infineon/pse84xgxs4.cfg
endif
ifeq (EXPLORER_A0,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__JLINK_DEVICE_CM0_CFG:=PSE84x_A0_CM0p
_MTB_RECIPE__OPENOCD_DEVICE_CFG:=infineon/pse84_a0.cfg
endif

# Derive JLink device alias from MPN structure:
#   Segger alias = PSE8{Line}{Features}{NVM}{SRAM}_{EPC}_{core}
# The first 8 characters of the MPN encode the device prefix directly.
# e.g. PSE846GPS4DBZC4 -> PSE846GP_EPC4_M33
_MTB_RECIPE__JLINK_MPN_BASE:=$(shell echo $(DEVICE) | sed 's/^\(.\{8\}\).*/\1/')
_MTB_RECIPE__JLINK_EPC:=EPC2
ifneq ($(filter EPC4,$(DEVICE_$(DEVICE)_FEATURES)),)
_MTB_RECIPE__JLINK_EPC:=EPC4
endif

# Programming always targets CM33 (secure boot entry point)
_MTB_RECIPE__JLINK_DEVICE_CFG_PROGRAM:=$(_MTB_RECIPE__JLINK_MPN_BASE)_$(_MTB_RECIPE__JLINK_EPC)_M33
ifeq (EXPLORER_A0,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__JLINK_DEVICE_CFG_PROGRAM:=PSE84x_A0_CM33_S
else
# Explorer B0
ifneq ($(filter PSE84_PSVP,$(DEFINES)),)
_MTB_RECIPE__JLINK_DEVICE_CFG_PROGRAM:=PSE84x_PSVP_CM33_S
endif
endif

ifeq ($(MTB_RECIPE__CORE),CM33)
# CM33 core
_MTB_RECIPE__JLINK_DEVICE_CFG:=$(_MTB_RECIPE__JLINK_MPN_BASE)_$(_MTB_RECIPE__JLINK_EPC)_M33
ifeq (EXPLORER_A0,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__JLINK_DEVICE_CFG:=PSE84x_A0_CM33_S
else
# Explorer B0
ifneq ($(filter PSE84_PSVP,$(DEFINES)),)
_MTB_RECIPE__JLINK_DEVICE_CFG:=PSE84x_PSVP_CM33_S
endif
endif
ifneq ($(filter NON_SECURE,$(VCORE_ATTRS)),)
_MTB_RECIPE__OPENOCD_RESET_TARGET:=cm33_ns
else
_MTB_RECIPE__OPENOCD_RESET_TARGET:=cm33
endif
else
# CM55 core
_MTB_RECIPE__OPENOCD_RESET_TARGET:=cm55
_MTB_RECIPE__JLINK_DEVICE_CFG:=$(_MTB_RECIPE__JLINK_MPN_BASE)_$(_MTB_RECIPE__JLINK_EPC)_M55
ifeq (EXPLORER_A0,$(_MTB_RECIPE__DEVICE_DIE))
_MTB_RECIPE__JLINK_DEVICE_CFG:=PSE84x_A0_CM55
endif
endif # MTB_RECIPE_CORE

ifneq ($(filter PSE84_PSVP,$(DEFINES)),)
_MTB_RECIPE__OPENOCD_BOARD=set BOARD psvp
endif

ifeq ($(MTB_PROBE_INTERFACE),jtag)
_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY?=adapter speed 8000;
else
_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY?=adapter speed 12000;
endif

_MTB_RECIPE__VSCODE_MULTI_CORE_TASKS_JSON_NAME:=tasks.json
_MTB_RECIPE__ERASE_TEMPLATE_FOLDER_NAME:=external

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET=false
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_MULTICORE_OTHER_RUN_COMMANDS:=monitor reset_halt cm55 multi$(_MTB_RECIPE__ECLIPSE_NEWLINE)flushregs

ifeq ($(MTB_RECIPE__CORE),CM33)
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__ECLIPSE_ADD_SYMBOL_PLACEHOLDER)monitor reset_halt $(_MTB_RECIPE__OPENOCD_RESET_TARGET) attach$(_MTB_RECIPE__ECLIPSE_NEWLINE)flushregs$(_MTB_RECIPE__ECLIPSE_NEWLINE)mon gdb_sync$(_MTB_RECIPE__ECLIPSE_NEWLINE)thread apply all stepi
else
_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_OTHER_RUN_COMMANDS=monitor reset_halt $(_MTB_RECIPE__OPENOCD_RESET_TARGET) attach$(_MTB_RECIPE__ECLIPSE_NEWLINE)flushregs$(_MTB_RECIPE__ECLIPSE_NEWLINE)mon gdb_sync$(_MTB_RECIPE__ECLIPSE_NEWLINE)thread apply all stepi

_MTB_RECIPE__ECLIPSE_OPENOCD_ATTACH_PRE_TARGET_CUSTOM_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)set ENABLE_CM55 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_port 3332$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
endif

ifeq ($(MTB_RECIPE__CORE),CM55)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_INIT_COMMANDS=monitor reset_halt cm55
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_CUSTOM_COMMANDS:=-c $(_MTB_RECIPE__ECLIPSE_QUOT)set ENABLE_CM55 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_port 3332$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
endif

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_PRE_TARGET_CUSTOM_COMMANDS:=-c $(_MTB_RECIPE__ECLIPSE_QUOT)set ENABLE_CM55 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_POST_TARGET_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cm33 configure -rtos auto -rtos-wipe-on-reset-halt 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__OPENOCD_CHIP_NAME).cm55 configure -rtos auto -rtos-wipe-on-reset-halt 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_breakpoint_override hard$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)init; reset init; $(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY) flash write_image erase $(_MTB_RECIPE__ECLIPSE_APP_PROG_FILE)$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)reset init$(_MTB_RECIPE__ECLIPSE_QUOT)

_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_POST_TARGET_COMMANDS=-c $(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__OPENOCD_CHIP_NAME).$(_MTB_RECIPE__OPENOCD_CORE_NAME) configure -rtos auto -rtos-wipe-on-reset-halt 1$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)gdb_breakpoint_override hard$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)init; reset init; $(_MTB_RECIPE__OPENOCD_PROBE_FREQUENCY) flash write_image erase $(_MTB_RECIPE__ECLIPSE_PROG_FILE)$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)-c $(_MTB_RECIPE__ECLIPSE_QUOT)reset init$(_MTB_RECIPE__ECLIPSE_QUOT)

ifneq ($(APPTYPE),ram)
# flash specific sequences
ifeq ($(MTB_RECIPE__CORE),CM33)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__ECLIPSE_ADD_SYMBOL_PLACEHOLDER)monitor reset_halt $(_MTB_RECIPE__OPENOCD_RESET_TARGET)
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_MULTICORE_OTHER_RUN_COMMANDS=monitor reset_halt $(_MTB_RECIPE__OPENOCD_RESET_TARGET)
else
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_OTHER_RUN_COMMANDS=monitor reset_halt cm55
endif
else
# RAM specific sequences
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_DO_SECOND_RESET=false
_MTB_RECIPE__ECLIPSE_OPENOCD_DEBUG_PRE_TARGET_CUSTOM_COMMANDS:=-c $(_MTB_RECIPE__ECLIPSE_QUOT)set ENABLE_ACQUIRE 0$(_MTB_RECIPE__ECLIPSE_QUOT)$(_MTB_RECIPE__ECLIPSE_NEWLINE)
endif

ifeq ($(MTB_RECIPE__CORE),CM33)
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_LOAD_IMAGE=true
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS=$(_MTB_RECIPE__ECLIPSE_ADD_SYMBOL_PLACEHOLDER)flushregs
else
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_LOAD_IMAGE=false
_MTB_RECIPE__ECLIPSE_JLINK_DEBUG_OTHER_RUN_COMMANDS=flushregs
endif
